### ISSUE TITLE
ERRO[0001] Error running FFUF

### ISSUE THREAD

**Issue by Teicu** [puzzlepeaches/ffufw#9]
I'm attempting to execute this tool on Mac OS, and I would appreciate any assistance. It's worth noting that ffuf is already installed.

sudo ./ffufw -o /Users/root/Desktop/output/ -i /Users/root/Desktop/target.txt -c /opt/ffufrc -v

_INFO[0001] Started scanning: http://testphp.vulnweb.com 
DEBU[0001] Running command: /usr/local/bin/ffuf -u http://testphp.vulnweb.com/FUZZ -config /opt/ffufrc -w /Users/root/.ffufw/wordlists/misc/raft-medium-files.txt -of json -od /Users/root/Desktop/output/http_testphp.vulnweb.com -o /Users/root/Desktop/output/http_testphp.vulnweb.com/results.raft-medium-files.json 
ERRO[0001] Error running FFUF: exit status 1 [URL: http://testphp.vulnweb.com] 
ERRO[0001] Error running FFUF: exit status 1 [URL: http://php.testsparker.com] 
ERRO[0001] Error running FFUF: exit status 1 [URL: http://testphp.vulnweb.com]_

**Comment by J005** [comment]
This fixed the same error for me

`touch ~/.ffufrc`

**Comment by puzzlepeaches** [comment]
I can't replicate this on my system. Closing this assuming the comment @J005 will fix in odd situations. Will reopen if someone can provide further troubleshooting information.

**Comment by puzzlepeaches** [comment]
Assuming this could have been an invalidly formatted ffufrc as well.

**Comment by Sh4d0wHunt3rX** [comment]
Hey, thanks for this tool : ) Unfortunately, I couldn't run it : ( Ubuntu 22.04

![image](https://github.com/user-attachments/assets/4c011779-acd7-4218-91a1-50ffcae06fc7)

**Comment by Sh4d0wHunt3rX** [comment]
@puzzlepeaches 

I guess it's because of -config part, Your script says 
INFO[0000] Could not find config file at                
INFO[0000] Continuing without config file

But it seems, it added -config anyway? And there is space after it.

![image](https://github.com/user-attachments/assets/d1cfd3de-7249-452c-a45a-784e77955b27)

Command work fine if I remove -config and run it manually, or if I run it with -c and path specified of .ffufrc

`ffufw -i /root/testing.txt -o /root/testing/ -c /root/.ffufrc`

Also, is it possible to add an option to remove request/responses at the end? I assume all good info in .json files, right?
